### ISSUE TITLE
Replace mysql_ with mysqli_

### ISSUE THREAD

**Issue by geekish** [geekish/enthusiast#1]
The MySQL extension has been _deprecated_ since PHP 5.5.0, and _removed_ as of 7.0.0. This is the primary issue with PHP version compatibility, and as such will be my first priority to implement.

See:
- [MySQLi reference](http://php.net/manual/en/book.mysqli.php)
- [How to convert MySQLi functions to MySQL functions](http://www.dummies.com/programming/databases/how-to-convert-mysqli-functions-to-mysql-functions/); good reference even if its intended purpose is the exact opposite of what I need.

**Comment by geekish** [comment]
Fixed in f5bf6e2edc2ec473bea3b975cd1793d1ee0665d2.

**Comment by emmarte** [comment]
Much, much love for you! <3 Does it mean we can use php 7 soon(ish) enough?

**Comment by geekish** [comment]
@emmarte That's my goal!
